//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MdbToTextConverter {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FormMessageStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FormMessageStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MdbToTextConverter.FormMessageStrings", typeof(FormMessageStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified directory does not exist..
        /// </summary>
        internal static string DirectoryDNE {
            get {
                return ResourceManager.GetString("DirectoryDNE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory contains no files with extension &quot;.mdb.&quot;.
        /// </summary>
        internal static string DirectoryHasNoMdbs {
            get {
                return ResourceManager.GetString("DirectoryHasNoMdbs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified file does not exist..
        /// </summary>
        internal static string FileDNE {
            get {
                return ResourceManager.GetString("FileDNE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a valid MDB file..
        /// </summary>
        internal static string InvalidMdbFile {
            get {
                return ResourceManager.GetString("InvalidMdbFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output complete..
        /// </summary>
        internal static string OutputComplete {
            get {
                return ResourceManager.GetString("OutputComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The output path you specified does not exist..
        /// </summary>
        internal static string OutputPathDNE {
            get {
                return ResourceManager.GetString("OutputPathDNE", resourceCulture);
            }
        }
    }
}
